---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/vgaupset/dat515-project/backend:latest
          ports:
            - name: http
              containerPort: 5277
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 100Mi
          #   limits:
          #     cpu: 300m
          #     memory: 200Mi
          # securityContext:
          #   readOnlyRootFilesystem: true
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - all
