---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/vgaupset/dat515-project/backend:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 800Mi
            limits:
              cpu: 300m
              memory: 1200Mi
        - image: mysql:8.0
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: MYSQL-ROOT-PASSWORD
                key: password
          - name: MYSQL_DATABASE
            value: posts
          - name: MYSQL_USER
            value: backend
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: MYSQL-ROOT-PASSWORD
                key: password
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 300Mi
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
          # securityContext:
          #   readOnlyRootFilesystem: true
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - all
