---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: frontend
  type: NodePort