---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - resources/backend-deployment.yaml
  - resources/backend-service.yaml
  - resources/frontend-deployment.yaml
  - resources/frontend-service.yaml
  - resources/backend-persistent-volume.yaml
